# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

# stub: ecs_bundler 1.0.0 ruby lib

Gem::Specification.new do |s|
  s.name = 'ecs_bundler'.freeze
  s.version = '1.0.0'

  s.required_rubygems_version = Gem::Requirement.new('>= 0'.freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ['lib'.freeze]
  s.authors = ['Anatolii Varanytsia'.freeze]
  s.date = '2017-06-01'
  s.description = 'Module for Bundler allowing the transfer of package dependencies to ECS for further legal and vulnerability analysis. See https://ecs.eacg.de for a detailed service description.'.freeze
  s.email = 'prizrack13@mail.ru'.freeze
  s.executables = ['ecs_bundler'.freeze]
  s.extra_rdoc_files = [
    'LICENSE.txt',
    'README.md'
  ]
  s.files = [
    '.document',
    '.ecsrc.json',
    '.rspec',
    '.travis.yml',
    'Gemfile',
    'Gemfile.lock',
    'LICENSE.txt',
    'README.md',
    'Rakefile',
    'VERSION',
    'bin/ecs_bundler',
    'ecs_bundler.gemspec',
    'lib/ecs_bundler.rb',
    'lib/ecs_bundler/bundler_scanner.rb',
    'lib/ecs_bundler/bundler_scanner/repository_finder.rb',
    'lib/ecs_bundler/config.rb',
    'lib/ecs_bundler/project_specification.rb',
    'lib/ecs_bundler/rest_client.rb',
    'lib/ecs_bundler/scan.rb',
    'lib/ecs_bundler/version.rb',
    'spec/fixtures/.ecsrc.json',
    'spec/fixtures/config.json',
    'spec/lib/ecs_bundler/bundler_scanner/repository_finder_spec.rb',
    'spec/lib/ecs_bundler/bundler_scanner_spec.rb',
    'spec/lib/ecs_bundler/config_spec.rb',
    'spec/lib/ecs_bundler/project_specification_spec.rb',
    'spec/lib/ecs_bundler/rest_client_spec.rb',
    'spec/lib/ecs_bundler/scan_spec.rb',
    'spec/lib/ecs_bundler_spec.rb',
    'spec/spec_helper.rb'
  ]
  s.homepage = 'http://github.com/eacg-gmbh/ecs-bundler'.freeze
  s.licenses = ['MIT'.freeze]
  s.rubygems_version = '2.6.9'.freeze
  s.summary = 'Module for Bundler allowing the transfer of package dependencies to ECS'.freeze

  if s.respond_to? :specification_version
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      s.add_runtime_dependency('bundler'.freeze, ['~> 1.0'])
      s.add_runtime_dependency('cli'.freeze, ['~> 1.3.1'])
      s.add_runtime_dependency('rest-client'.freeze, ['~> 2.0.2'])
      s.add_development_dependency('jeweler'.freeze, ['~> 2.3.5'])
      s.add_development_dependency('rdoc'.freeze, ['~> 5.1.0'])
      s.add_development_dependency('rspec'.freeze, ['~> 3.4'])
      s.add_development_dependency('rspec-mocks'.freeze, ['>= 0'])
      s.add_development_dependency('rubocop'.freeze, ['>= 0'])
      s.add_development_dependency('shoulda'.freeze, ['>= 0'])
      s.add_development_dependency('simplecov'.freeze, ['>= 0'])
    else
      s.add_dependency('bundler'.freeze, ['~> 1.0'])
      s.add_dependency('cli'.freeze, ['~> 1.3.1'])
      s.add_dependency('rest-client'.freeze, ['~> 2.0.2'])
      s.add_dependency('jeweler'.freeze, ['~> 2.3.5'])
      s.add_dependency('rdoc'.freeze, ['~> 5.1.0'])
      s.add_dependency('rspec'.freeze, ['~> 3.4'])
      s.add_dependency('rspec-mocks'.freeze, ['>= 0'])
      s.add_dependency('rubocop'.freeze, ['>= 0'])
      s.add_dependency('shoulda'.freeze, ['>= 0'])
      s.add_dependency('simplecov'.freeze, ['>= 0'])
    end
  else
    s.add_dependency('bundler'.freeze, ['~> 1.0'])
    s.add_dependency('cli'.freeze, ['~> 1.3.1'])
    s.add_dependency('rest-client'.freeze, ['~> 2.0.2'])
    s.add_dependency('jeweler'.freeze, ['~> 2.3.5'])
    s.add_dependency('rdoc'.freeze, ['~> 5.1.0'])
    s.add_dependency('rspec'.freeze, ['~> 3.4'])
    s.add_dependency('rspec-mocks'.freeze, ['>= 0'])
    s.add_dependency('rubocop'.freeze, ['>= 0'])
    s.add_dependency('shoulda'.freeze, ['>= 0'])
    s.add_dependency('simplecov'.freeze, ['>= 0'])
  end
end
